export const PATHS = {
	AUTH: {
		LOGIN: "/login",
		FORGOT_PASSWORD: "/forgot-password",
	},
	DASHBOARD: "/dashboard",
	ACADEMICS: {
		ROOT: "/academics",
		CLASSES: {
			ROOT: "/academics/classes",
			CREATE: "/academics/classes/create",
			EDIT: (id: number | string) => `/academics/classes/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/classes/${id}/details`,
		},
		SUBJECTS: {
			ROOT: "/academics/subjects",
			CREATE: "/academics/subjects/create",
			EDIT: (id: number | string) => `/academics/subjects/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/subjects/${id}/details`,
		},
		SYLLABUS: {
			ROOT: "/academics/syllabus",
			CREATE: "/academics/syllabus/create",
			EDIT: (id: number | string) => `/academics/syllabus/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/syllabus/${id}/details`,
		},
		TIMETABLE: {
			ROOT: "/academics/timetable",
			CREATE: "/academics/timetable/create",
			EDIT: (id: number | string) => `/academics/timetable/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/timetable/${id}/details`,
		},
		HOMEWORK: {
			ROOT: "/academics/homework",
			CREATE: "/academics/homework/create",
			EDIT: (id: number | string) => `/academics/homework/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/homework/${id}/details`,
		},
		ONLINE_CLASSES: {
			ROOT: "/academics/online-classes",
			CREATE: "/academics/online-classes/create",
			EDIT: (id: number | string) => `/academics/online-classes/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/online-classes/${id}/details`,
		},
		SHIFTS: {
			ROOT: "/academics/shifts",
			CREATE: "/academics/shifts/create",
			EDIT: (id: number | string) => `/academics/shifts/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/shifts/${id}/details`,
		},
		SESSIONS: {
			ROOT: "/academics/sessions",
			CREATE: "/academics/sessions/create",
			EDIT: (id: number | string) => `/academics/sessions/${id}/edit`,
			DETAILS: (id: number | string) => `/academics/sessions/${id}/details`,
		},
	},
	ADMISSION: {
		ROOT: "/admission",
		NEW: {
			ROOT: "/admission/new",
			CREATE: "/admission/new/create",
			EDIT: (id: number | string) => `/admission/new/${id}/edit`,
			DETAILS: (id: number | string) => `/admission/new/${id}/details`,
		},
		LIST: {
			ROOT: "/admission/list",
			CREATE: "/admission/list/create",
			EDIT: (id: number | string) => `/admission/list/${id}/edit`,
			DETAILS: (id: number | string) => `/admission/list/${id}/details`,
		},
		PORTAL: {
			ROOT: "/admission/portal",
			CREATE: "/admission/portal/create",
			EDIT: (id: number | string) => `/admission/portal/${id}/edit`,
			DETAILS: (id: number | string) => `/admission/portal/${id}/details`,
		},
		TRANSFER: {
			ROOT: "/admission/transfer",
			CREATE: "/admission/transfer/create",
			EDIT: (id: number | string) => `/admission/transfer/${id}/edit`,
			DETAILS: (id: number | string) => `/admission/transfer/${id}/details`,
		},
		SETTINGS: {
			ROOT: "/admission/settings",
			CREATE: "/admission/settings/create",
			EDIT: (id: number | string) => `/admission/settings/${id}/edit`,
			DETAILS: (id: number | string) => `/admission/settings/${id}/details`,
		},
	},
	STUDENTS: {
		ROOT: "/students",
		DIRECTORY: {
			ROOT: "/students/directory",
			CREATE: "/students/directory/create",
			EDIT: (id: number | string) => `/students/directory/${id}/edit`,
			DETAILS: (id: number | string) => `/students/directory/${id}/details`,
		},
		ATTENDANCE: {
			ROOT: "/students/attendance",
			CREATE: "/students/attendance/create",
			EDIT: (id: number | string) => `/students/attendance/${id}/edit`,
			DETAILS: (id: number | string) => `/students/attendance/${id}/details`,
		},
		PROFILE: {
			ROOT: "/students/profile",
			CREATE: "/students/profile/create",
			EDIT: (id: number | string) => `/students/profile/${id}/edit`,
			DETAILS: (id: number | string) => `/students/profile/${id}/details`,
		},
		PROMOTION: {
			ROOT: "/students/promotion",
			CREATE: "/students/promotion/create",
			EDIT: (id: number | string) => `/students/promotion/${id}/edit`,
			DETAILS: (id: number | string) => `/students/promotion/${id}/details`,
		},
		ID_CARDS: {
			ROOT: "/students/id-cards",
			CREATE: "/students/id-cards/create",
			EDIT: (id: number | string) => `/students/id-cards/${id}/edit`,
			DETAILS: (id: number | string) => `/students/id-cards/${id}/details`,
		},
		CERTIFICATES: {
			ROOT: "/students/certificates",
			CREATE: "/students/certificates/create",
			EDIT: (id: number | string) => `/students/certificates/${id}/edit`,
			DETAILS: (id: number | string) => `/students/certificates/${id}/details`,
		},
		BEHAVIOR: {
			ROOT: "/students/behavior",
			CREATE: "/students/behavior/create",
			EDIT: (id: number | string) => `/students/behavior/${id}/edit`,
			DETAILS: (id: number | string) => `/students/behavior/${id}/details`,
		},
	},
	STAFF: {
		ROOT: "/staff",
		DIRECTORY: {
			ROOT: "/staff/directory",
			CREATE: "/staff/directory/create",
			EDIT: (id: number | string) => `/staff/directory/${id}/edit`,
			DETAILS: (id: number | string) => `/staff/directory/${id}/details`,
		},
		TEACHERS: {
			ROOT: "/staff/teachers",
			CREATE: "/staff/teachers/create",
			EDIT: (id: number | string) => `/staff/teachers/${id}/edit`,
			DETAILS: (id: number | string) => `/staff/teachers/${id}/details`,
		},
		ATTENDANCE: {
			ROOT: "/staff/attendance",
			CREATE: "/staff/attendance/create",
			EDIT: (id: number | string) => `/staff/attendance/${id}/edit`,
			DETAILS: (id: number | string) => `/staff/attendance/${id}/details`,
		},
		DEPARTMENTS: {
			ROOT: "/staff/departments",
			CREATE: "/staff/departments/create",
			EDIT: (id: number | string) => `/staff/departments/${id}/edit`,
			DETAILS: (id: number | string) => `/staff/departments/${id}/details`,
		},
		PERFORMANCE: {
			ROOT: "/staff/performance",
			CREATE: "/staff/performance/create",
			EDIT: (id: number | string) => `/staff/performance/${id}/edit`,
			DETAILS: (id: number | string) => `/staff/performance/${id}/details`,
		},
	},
	PARENTS: {
		ROOT: "/parents",
		DIRECTORY: {
			ROOT: "/parents/directory",
			CREATE: "/parents/directory/create",
			EDIT: (id: number | string) => `/parents/directory/${id}/edit`,
			DETAILS: (id: number | string) => `/parents/directory/${id}/details`,
		},
		PORTAL: {
			ROOT: "/parents/portal",
			CREATE: "/parents/portal/create",
			EDIT: (id: number | string) => `/parents/portal/${id}/edit`,
			DETAILS: (id: number | string) => `/parents/portal/${id}/details`,
		},
	},
	FINANCE: {
		ROOT: "/finance",
		FEES: {
			ROOT: "/finance/fees",
			CREATE: "/finance/fees/create",
			EDIT: (id: number | string) => `/finance/fees/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/fees/${id}/details`,
		},
		EXPENSES: {
			ROOT: "/finance/expenses",
			CREATE: "/finance/expenses/create",
			EDIT: (id: number | string) => `/finance/expenses/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/expenses/${id}/details`,
		},
		PAYROLL: {
			ROOT: "/finance/payroll",
			CREATE: "/finance/payroll/create",
			EDIT: (id: number | string) => `/finance/payroll/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/payroll/${id}/details`,
		},
		LEDGER: {
			ROOT: "/finance/ledger",
			CREATE: "/finance/ledger/create",
			EDIT: (id: number | string) => `/finance/ledger/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/ledger/${id}/details`,
		},
		SCHOLARSHIPS: {
			ROOT: "/finance/scholarships",
			CREATE: "/finance/scholarships/create",
			EDIT: (id: number | string) => `/finance/scholarships/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/scholarships/${id}/details`,
		},
		BUDGET: {
			ROOT: "/finance/budget",
			CREATE: "/finance/budget/create",
			EDIT: (id: number | string) => `/finance/budget/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/budget/${id}/details`,
		},
		VOUCHERS: {
			ROOT: "/finance/vouchers",
			CREATE: "/finance/vouchers/create",
			EDIT: (id: number | string) => `/finance/vouchers/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/vouchers/${id}/details`,
		},
		BANK_ACCOUNTS: {
			ROOT: "/finance/bank-accounts",
			CREATE: "/finance/bank-accounts/create",
			EDIT: (id: number | string) => `/finance/bank-accounts/${id}/edit`,
			DETAILS: (id: number | string) => `/finance/bank-accounts/${id}/details`,
		},
	},
	HR: {
		ROOT: "/hr",
		LEAVE: {
			ROOT: "/hr/leave",
			CREATE: "/hr/leave/create",
			EDIT: (id: number | string) => `/hr/leave/${id}/edit`,
			DETAILS: (id: number | string) => `/hr/leave/${id}/details`,
		},
		LOAN: {
			ROOT: "/hr/loan",
			CREATE: "/hr/loan/create",
			EDIT: (id: number | string) => `/hr/loan/${id}/edit`,
			DETAILS: (id: number | string) => `/hr/loan/${id}/details`,
		},
		APPRAISAL: {
			ROOT: "/hr/appraisal",
			CREATE: "/hr/appraisal/create",
			EDIT: (id: number | string) => `/hr/appraisal/${id}/edit`,
			DETAILS: (id: number | string) => `/hr/appraisal/${id}/details`,
		},
	},
	EXAMINATIONS: {
		ROOT: "/examinations",
		SCHEDULE: {
			ROOT: "/examinations/schedule",
			CREATE: "/examinations/schedule/create",
			EDIT: (id: number | string) => `/examinations/schedule/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/schedule/${id}/details`,
		},
		MARKS: {
			ROOT: "/examinations/marks",
			CREATE: "/examinations/marks/create",
			EDIT: (id: number | string) => `/examinations/marks/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/marks/${id}/details`,
		},
		RESULTS: {
			ROOT: "/examinations/results",
			CREATE: "/examinations/results/create",
			EDIT: (id: number | string) => `/examinations/results/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/results/${id}/details`,
		},
		REPORT_CARDS: {
			ROOT: "/examinations/report-cards",
			CREATE: "/examinations/report-cards/create",
			EDIT: (id: number | string) => `/examinations/report-cards/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/report-cards/${id}/details`,
		},
		QUESTION_BANK: {
			ROOT: "/examinations/question-bank",
			CREATE: "/examinations/question-bank/create",
			EDIT: (id: number | string) => `/examinations/question-bank/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/question-bank/${id}/details`,
		},
		SETTINGS: {
			ROOT: "/examinations/settings",
			CREATE: "/examinations/settings/create",
			EDIT: (id: number | string) => `/examinations/settings/${id}/edit`,
			DETAILS: (id: number | string) => `/examinations/settings/${id}/details`,
		},
	},
	LIBRARY: {
		ROOT: "/library",
		CATALOG: {
			ROOT: "/library/catalog",
			CREATE: "/library/catalog/create",
			EDIT: (id: number | string) => `/library/catalog/${id}/edit`,
			DETAILS: (id: number | string) => `/library/catalog/${id}/details`,
		},
		ISSUE_RETURN: {
			ROOT: "/library/issue-return",
			CREATE: "/library/issue-return/create",
			EDIT: (id: number | string) => `/library/issue-return/${id}/edit`,
			DETAILS: (id: number | string) => `/library/issue-return/${id}/details`,
		},
		FINES: {
			ROOT: "/library/fines",
			CREATE: "/library/fines/create",
			EDIT: (id: number | string) => `/library/fines/${id}/edit`,
			DETAILS: (id: number | string) => `/library/fines/${id}/details`,
		},
		REPORTS: {
			ROOT: "/library/reports",
			CREATE: "/library/reports/create",
			EDIT: (id: number | string) => `/library/reports/${id}/edit`,
			DETAILS: (id: number | string) => `/library/reports/${id}/details`,
		},
	},
	COMMUNICATIONS: {
		ROOT: "/communications",
		ANNOUNCEMENTS: {
			ROOT: "/communications/announcements",
			CREATE: "/communications/announcements/create",
			EDIT: (id: number | string) => `/communications/announcements/${id}/edit`,
			DETAILS: (id: number | string) => `/communications/announcements/${id}/details`,
		},
		NOTICE_BOARD: {
			ROOT: "/communications/notice-board",
			CREATE: "/communications/notice-board/create",
			EDIT: (id: number | string) => `/communications/notice-board/${id}/edit`,
			DETAILS: (id: number | string) => `/communications/notice-board/${id}/details`,
		},
		MESSAGES: {
			ROOT: "/communications/messages",
			CREATE: "/communications/messages/create",
			EDIT: (id: number | string) => `/communications/messages/${id}/edit`,
			DETAILS: (id: number | string) => `/communications/messages/${id}/details`,
		},
		COMPLAINTS: {
			ROOT: "/communications/complaints",
			CREATE: "/communications/complaints/create",
			EDIT: (id: number | string) => `/communications/complaints/${id}/edit`,
			DETAILS: (id: number | string) => `/communications/complaints/${id}/details`,
		},
	},
	EVENTS: {
		ROOT: "/events",
		SCHEDULING: {
			ROOT: "/events/scheduling",
			CREATE: "/events/scheduling/create",
			EDIT: (id: number | string) => `/events/scheduling/${id}/edit`,
			DETAILS: (id: number | string) => `/events/scheduling/${id}/details`,
		},
		PARTICIPANTS: {
			ROOT: "/events/participants",
			CREATE: "/events/participants/create",
			EDIT: (id: number | string) => `/events/participants/${id}/edit`,
			DETAILS: (id: number | string) => `/events/participants/${id}/details`,
		},
		GALLERY: {
			ROOT: "/events/gallery",
			CREATE: "/events/gallery/create",
			EDIT: (id: number | string) => `/events/gallery/${id}/edit`,
			DETAILS: (id: number | string) => `/events/gallery/${id}/details`,
		},
	},
	TRANSPORT: {
		ROOT: "/transport",
		ROUTES: {
			ROOT: "/transport/routes",
			CREATE: "/transport/routes/create",
			EDIT: (id: number | string) => `/transport/routes/${id}/edit`,
			DETAILS: (id: number | string) => `/transport/routes/${id}/details`,
		},
		VEHICLES: {
			ROOT: "/transport/vehicles",
			CREATE: "/transport/vehicles/create",
			EDIT: (id: number | string) => `/transport/vehicles/${id}/edit`,
			DETAILS: (id: number | string) => `/transport/vehicles/${id}/details`,
		},
		ASSIGNMENT: {
			ROOT: "/transport/assignment",
			CREATE: "/transport/assignment/create",
			EDIT: (id: number | string) => `/transport/assignment/${id}/edit`,
			DETAILS: (id: number | string) => `/transport/assignment/${id}/details`,
		},
		ATTENDANCE: {
			ROOT: "/transport/attendance",
			CREATE: "/transport/attendance/create",
			EDIT: (id: number | string) => `/transport/attendance/${id}/edit`,
			DETAILS: (id: number | string) => `/transport/attendance/${id}/details`,
		},
	},
	CANTEEN: {
		ROOT: "/canteen",
		MENU: {
			ROOT: "/canteen/menu",
			CREATE: "/canteen/menu/create",
			EDIT: (id: number | string) => `/canteen/menu/${id}/edit`,
			DETAILS: (id: number | string) => `/canteen/menu/${id}/details`,
		},
		SALES: {
			ROOT: "/canteen/sales",
			CREATE: "/canteen/sales/create",
			EDIT: (id: number | string) => `/canteen/sales/${id}/edit`,
			DETAILS: (id: number | string) => `/canteen/sales/${id}/details`,
		},
		EXPENSE: {
			ROOT: "/canteen/expense",
			CREATE: "/canteen/expense/create",
			EDIT: (id: number | string) => `/canteen/expense/${id}/edit`,
			DETAILS: (id: number | string) => `/canteen/expense/${id}/details`,
		},
	},
	REPORTS: {
		ROOT: "/reports",
		ACADEMIC: {
			ROOT: "/reports/academic",
			CREATE: "/reports/academic/create",
			EDIT: (id: number | string) => `/reports/academic/${id}/edit`,
			DETAILS: (id: number | string) => `/reports/academic/${id}/details`,
		},
		FINANCE: {
			ROOT: "/reports/finance",
			CREATE: "/reports/finance/create",
			EDIT: (id: number | string) => `/reports/finance/${id}/edit`,
			DETAILS: (id: number | string) => `/reports/finance/${id}/details`,
		},
		STUDENT: {
			ROOT: "/reports/student",
			CREATE: "/reports/student/create",
			EDIT: (id: number | string) => `/reports/student/${id}/edit`,
			DETAILS: (id: number | string) => `/reports/student/${id}/details`,
		},
		SCHEDULED: {
			ROOT: "/reports/scheduled",
			CREATE: "/reports/scheduled/create",
			EDIT: (id: number | string) => `/reports/scheduled/${id}/edit`,
			DETAILS: (id: number | string) => `/reports/scheduled/${id}/details`,
		},
	},
	ROLES: {
		ROOT: "/roles",
		MANAGEMENT: {
			ROOT: "/roles/management",
			CREATE: "/roles/management/create",
			EDIT: (id: number | string) => `/roles/management/${id}/edit`,
			DETAILS: (id: number | string) => `/roles/management/${id}/details`,
		},
		MATRIX: {
			ROOT: "/roles/matrix",
			CREATE: "/roles/matrix/create",
			EDIT: (id: number | string) => `/roles/matrix/${id}/edit`,
			DETAILS: (id: number | string) => `/roles/matrix/${id}/details`,
		},
	},
	SETTINGS: {
		ROOT: "/settings",
		PROFILE: {
			ROOT: "/settings/profile",
			CREATE: "/settings/profile/create",
			EDIT: (id: number | string) => `/settings/profile/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/profile/${id}/details`,
		},
		USERS: {
			ROOT: "/settings/users",
			CREATE: "/settings/users/create",
			EDIT: (id: number | string) => `/settings/users/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/users/${id}/details`,
		},
		INTEGRATIONS: {
			ROOT: "/settings/integrations",
			CREATE: "/settings/integrations/create",
			EDIT: (id: number | string) => `/settings/integrations/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/integrations/${id}/details`,
		},
		LOCALIZATION: {
			ROOT: "/settings/localization",
			CREATE: "/settings/localization/create",
			EDIT: (id: number | string) => `/settings/localization/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/localization/${id}/details`,
		},
		BACKUP: {
			ROOT: "/settings/backup",
			CREATE: "/settings/backup/create",
			EDIT: (id: number | string) => `/settings/backup/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/backup/${id}/details`,
		},
		AUDIT: {
			ROOT: "/settings/audit",
			CREATE: "/settings/audit/create",
			EDIT: (id: number | string) => `/settings/audit/${id}/edit`,
			DETAILS: (id: number | string) => `/settings/audit/${id}/details`,
		},
	},
} as const;
