export const PERMISSIONS = {
	DASHBOARD: {
		VIEW: "dashboard.view",
	},
	ACADEMICS: {
		VIEW: "academics.view",
		ALL: "academics.all",
		CLASSES: {
			ALL: "academics.classes.all",
			VIEW: "academics.classes.view",
			CREATE: "academics.classes.create",
			EDIT: "academics.classes.edit",
			DELETE: "academics.classes.delete",
		},
		SUBJECTS: {
			ALL: "academics.subjects.all",
			VIEW: "academics.subjects.view",
			CREATE: "academics.subjects.create",
			EDIT: "academics.subjects.edit",
			DELETE: "academics.subjects.delete",
		},
		SYLLABUS: {
			ALL: "academics.syllabus.all",
			VIEW: "academics.syllabus.view",
			CREATE: "academics.syllabus.create",
			EDIT: "academics.syllabus.edit",
			DELETE: "academics.syllabus.delete",
		},
		TIMETABLE: {
			ALL: "academics.timetable.all",
			VIEW: "academics.timetable.view",
			CREATE: "academics.timetable.create",
			EDIT: "academics.timetable.edit",
			DELETE: "academics.timetable.delete",
		},
		HOMEWORK: {
			ALL: "academics.homework.all",
			VIEW: "academics.homework.view",
			CREATE: "academics.homework.create",
			EDIT: "academics.homework.edit",
			DELETE: "academics.homework.delete",
		},
		ONLINE_CLASSES: {
			ALL: "academics.online_classes.all",
			VIEW: "academics.online_classes.view",
			CREATE: "academics.online_classes.create",
			EDIT: "academics.online_classes.edit",
			DELETE: "academics.online_classes.delete",
		},
		SHIFTS: {
			ALL: "academics.shifts.all",
			VIEW: "academics.shifts.view",
			CREATE: "academics.shifts.create",
			EDIT: "academics.shifts.edit",
			DELETE: "academics.shifts.delete",
		},
		SESSIONS: {
			ALL: "academics.sessions.all",
			VIEW: "academics.sessions.view",
			CREATE: "academics.sessions.create",
			EDIT: "academics.sessions.edit",
			DELETE: "academics.sessions.delete",
		},
	},
	ADMISSION: {
		VIEW: "admission.view",
		ALL: "admission.all",
		NEW: {
			ALL: "admission.new.all",
			VIEW: "admission.new.view",
			CREATE: "admission.new.create",
			EDIT: "admission.new.edit",
			DELETE: "admission.new.delete",
		},
		LIST: {
			ALL: "admission.list.all",
			VIEW: "admission.list.view",
			CREATE: "admission.list.create",
			EDIT: "admission.list.edit",
			DELETE: "admission.list.delete",
		},
		PORTAL: {
			ALL: "admission.portal.all",
			VIEW: "admission.portal.view",
			CREATE: "admission.portal.create",
			EDIT: "admission.portal.edit",
			DELETE: "admission.portal.delete",
		},
		TRANSFER: {
			ALL: "admission.transfer.all",
			VIEW: "admission.transfer.view",
			CREATE: "admission.transfer.create",
			EDIT: "admission.transfer.edit",
			DELETE: "admission.transfer.delete",
		},
		SETTINGS: {
			ALL: "admission.settings.all",
			VIEW: "admission.settings.view",
			CREATE: "admission.settings.create",
			EDIT: "admission.settings.edit",
			DELETE: "admission.settings.delete",
		},
	},
	STUDENTS: {
		VIEW: "students.view",
		ALL: "students.all",
		DIRECTORY: {
			ALL: "students.directory.all",
			VIEW: "students.directory.view",
			CREATE: "students.directory.create",
			EDIT: "students.directory.edit",
			DELETE: "students.directory.delete",
		},
		ATTENDANCE: {
			ALL: "students.attendance.all",
			VIEW: "students.attendance.view",
			CREATE: "students.attendance.create",
			EDIT: "students.attendance.edit",
			DELETE: "students.attendance.delete",
		},
		PROFILE: {
			ALL: "students.profile.all",
			VIEW: "students.profile.view",
			CREATE: "students.profile.create",
			EDIT: "students.profile.edit",
			DELETE: "students.profile.delete",
		},
		PROMOTION: {
			ALL: "students.promotion.all",
			VIEW: "students.promotion.view",
			CREATE: "students.promotion.create",
			EDIT: "students.promotion.edit",
			DELETE: "students.promotion.delete",
		},
		ID_CARDS: {
			ALL: "students.id_cards.all",
			VIEW: "students.id_cards.view",
			CREATE: "students.id_cards.create",
			EDIT: "students.id_cards.edit",
			DELETE: "students.id_cards.delete",
		},
		CERTIFICATES: {
			ALL: "students.certificates.all",
			VIEW: "students.certificates.view",
			CREATE: "students.certificates.create",
			EDIT: "students.certificates.edit",
			DELETE: "students.certificates.delete",
		},
		BEHAVIOR: {
			ALL: "students.behavior.all",
			VIEW: "students.behavior.view",
			CREATE: "students.behavior.create",
			EDIT: "students.behavior.edit",
			DELETE: "students.behavior.delete",
		},
	},
	STAFF: {
		VIEW: "staff.view",
		ALL: "staff.all",
		DIRECTORY: {
			ALL: "staff.directory.all",
			VIEW: "staff.directory.view",
			CREATE: "staff.directory.create",
			EDIT: "staff.directory.edit",
			DELETE: "staff.directory.delete",
		},
		TEACHERS: {
			ALL: "staff.teachers.all",
			VIEW: "staff.teachers.view",
			CREATE: "staff.teachers.create",
			EDIT: "staff.teachers.edit",
			DELETE: "staff.teachers.delete",
		},
		ATTENDANCE: {
			ALL: "staff.attendance.all",
			VIEW: "staff.attendance.view",
			CREATE: "staff.attendance.create",
			EDIT: "staff.attendance.edit",
			DELETE: "staff.attendance.delete",
		},
		DEPARTMENTS: {
			ALL: "staff.departments.all",
			VIEW: "staff.departments.view",
			CREATE: "staff.departments.create",
			EDIT: "staff.departments.edit",
			DELETE: "staff.departments.delete",
		},
		PERFORMANCE: {
			ALL: "staff.performance.all",
			VIEW: "staff.performance.view",
			CREATE: "staff.performance.create",
			EDIT: "staff.performance.edit",
			DELETE: "staff.performance.delete",
		},
	},
	PARENTS: {
		VIEW: "parents.view",
		ALL: "parents.all",
		DIRECTORY: {
			ALL: "parents.directory.all",
			VIEW: "parents.directory.view",
			CREATE: "parents.directory.create",
			EDIT: "parents.directory.edit",
			DELETE: "parents.directory.delete",
		},
		PORTAL: {
			ALL: "parents.portal.all",
			VIEW: "parents.portal.view",
			CREATE: "parents.portal.create",
			EDIT: "parents.portal.edit",
			DELETE: "parents.portal.delete",
		},
	},
	FINANCE: {
		VIEW: "finance.view",
		ALL: "finance.all",
		FEES: {
			ALL: "finance.fees.all",
			VIEW: "finance.fees.view",
			CREATE: "finance.fees.create",
			EDIT: "finance.fees.edit",
			DELETE: "finance.fees.delete",
		},
		EXPENSES: {
			ALL: "finance.expenses.all",
			VIEW: "finance.expenses.view",
			CREATE: "finance.expenses.create",
			EDIT: "finance.expenses.edit",
			DELETE: "finance.expenses.delete",
		},
		PAYROLL: {
			ALL: "finance.payroll.all",
			VIEW: "finance.payroll.view",
			CREATE: "finance.payroll.create",
			EDIT: "finance.payroll.edit",
			DELETE: "finance.payroll.delete",
		},
		LEDGER: {
			ALL: "finance.ledger.all",
			VIEW: "finance.ledger.view",
			CREATE: "finance.ledger.create",
			EDIT: "finance.ledger.edit",
			DELETE: "finance.ledger.delete",
		},
		SCHOLARSHIPS: {
			ALL: "finance.scholarships.all",
			VIEW: "finance.scholarships.view",
			CREATE: "finance.scholarships.create",
			EDIT: "finance.scholarships.edit",
			DELETE: "finance.scholarships.delete",
		},
		BUDGET: {
			ALL: "finance.budget.all",
			VIEW: "finance.budget.view",
			CREATE: "finance.budget.create",
			EDIT: "finance.budget.edit",
			DELETE: "finance.budget.delete",
		},
		VOUCHERS: {
			ALL: "finance.vouchers.all",
			VIEW: "finance.vouchers.view",
			CREATE: "finance.vouchers.create",
			EDIT: "finance.vouchers.edit",
			DELETE: "finance.vouchers.delete",
		},
		BANK_ACCOUNTS: {
			ALL: "finance.bank_accounts.all",
			VIEW: "finance.bank_accounts.view",
			CREATE: "finance.bank_accounts.create",
			EDIT: "finance.bank_accounts.edit",
			DELETE: "finance.bank_accounts.delete",
		},
	},
	HR: {
		VIEW: "hr.view",
		ALL: "hr.all",
		LEAVE: {
			ALL: "hr.leave.all",
			VIEW: "hr.leave.view",
			CREATE: "hr.leave.create",
			EDIT: "hr.leave.edit",
			DELETE: "hr.leave.delete",
		},
		LOAN: {
			ALL: "hr.loan.all",
			VIEW: "hr.loan.view",
			CREATE: "hr.loan.create",
			EDIT: "hr.loan.edit",
			DELETE: "hr.loan.delete",
		},
		APPRAISAL: {
			ALL: "hr.appraisal.all",
			VIEW: "hr.appraisal.view",
			CREATE: "hr.appraisal.create",
			EDIT: "hr.appraisal.edit",
			DELETE: "hr.appraisal.delete",
		},
	},
	EXAMINATIONS: {
		VIEW: "examinations.view",
		ALL: "examinations.all",
		SCHEDULE: {
			ALL: "examinations.schedule.all",
			VIEW: "examinations.schedule.view",
			CREATE: "examinations.schedule.create",
			EDIT: "examinations.schedule.edit",
			DELETE: "examinations.schedule.delete",
		},
		MARKS: {
			ALL: "examinations.marks.all",
			VIEW: "examinations.marks.view",
			CREATE: "examinations.marks.create",
			EDIT: "examinations.marks.edit",
			DELETE: "examinations.marks.delete",
		},
		RESULTS: {
			ALL: "examinations.results.all",
			VIEW: "examinations.results.view",
			CREATE: "examinations.results.create",
			EDIT: "examinations.results.edit",
			DELETE: "examinations.results.delete",
		},
		REPORT_CARDS: {
			ALL: "examinations.report_cards.all",
			VIEW: "examinations.report_cards.view",
			CREATE: "examinations.report_cards.create",
			EDIT: "examinations.report_cards.edit",
			DELETE: "examinations.report_cards.delete",
		},
		QUESTION_BANK: {
			ALL: "examinations.question_bank.all",
			VIEW: "examinations.question_bank.view",
			CREATE: "examinations.question_bank.create",
			EDIT: "examinations.question_bank.edit",
			DELETE: "examinations.question_bank.delete",
		},
		SETTINGS: {
			ALL: "examinations.settings.all",
			VIEW: "examinations.settings.view",
			CREATE: "examinations.settings.create",
			EDIT: "examinations.settings.edit",
			DELETE: "examinations.settings.delete",
		},
	},
	LIBRARY: {
		VIEW: "library.view",
		ALL: "library.all",
		CATALOG: {
			ALL: "library.catalog.all",
			VIEW: "library.catalog.view",
			CREATE: "library.catalog.create",
			EDIT: "library.catalog.edit",
			DELETE: "library.catalog.delete",
		},
		ISSUE_RETURN: {
			ALL: "library.issue_return.all",
			VIEW: "library.issue_return.view",
			CREATE: "library.issue_return.create",
			EDIT: "library.issue_return.edit",
			DELETE: "library.issue_return.delete",
		},
		FINES: {
			ALL: "library.fines.all",
			VIEW: "library.fines.view",
			CREATE: "library.fines.create",
			EDIT: "library.fines.edit",
			DELETE: "library.fines.delete",
		},
		REPORTS: {
			ALL: "library.reports.all",
			VIEW: "library.reports.view",
			CREATE: "library.reports.create",
			EDIT: "library.reports.edit",
			DELETE: "library.reports.delete",
		},
	},
	COMMUNICATIONS: {
		VIEW: "communications.view",
		ALL: "communications.all",
		ANNOUNCEMENTS: {
			ALL: "communications.announcements.all",
			VIEW: "communications.announcements.view",
			CREATE: "communications.announcements.create",
			EDIT: "communications.announcements.edit",
			DELETE: "communications.announcements.delete",
		},
		NOTICE_BOARD: {
			ALL: "communications.notice_board.all",
			VIEW: "communications.notice_board.view",
			CREATE: "communications.notice_board.create",
			EDIT: "communications.notice_board.edit",
			DELETE: "communications.notice_board.delete",
		},
		MESSAGES: {
			ALL: "communications.messages.all",
			VIEW: "communications.messages.view",
			CREATE: "communications.messages.create",
			EDIT: "communications.messages.edit",
			DELETE: "communications.messages.delete",
		},
		COMPLAINTS: {
			ALL: "communications.complaints.all",
			VIEW: "communications.complaints.view",
			CREATE: "communications.complaints.create",
			EDIT: "communications.complaints.edit",
			DELETE: "communications.complaints.delete",
		},
	},
	EVENTS: {
		VIEW: "events.view",
		ALL: "events.all",
		SCHEDULING: {
			ALL: "events.scheduling.all",
			VIEW: "events.scheduling.view",
			CREATE: "events.scheduling.create",
			EDIT: "events.scheduling.edit",
			DELETE: "events.scheduling.delete",
		},
		PARTICIPANTS: {
			ALL: "events.participants.all",
			VIEW: "events.participants.view",
			CREATE: "events.participants.create",
			EDIT: "events.participants.edit",
			DELETE: "events.participants.delete",
		},
		GALLERY: {
			ALL: "events.gallery.all",
			VIEW: "events.gallery.view",
			CREATE: "events.gallery.create",
			EDIT: "events.gallery.edit",
			DELETE: "events.gallery.delete",
		},
	},
	TRANSPORT: {
		VIEW: "transport.view",
		ALL: "transport.all",
		ROUTES: {
			ALL: "transport.routes.all",
			VIEW: "transport.routes.view",
			CREATE: "transport.routes.create",
			EDIT: "transport.routes.edit",
			DELETE: "transport.routes.delete",
		},
		VEHICLES: {
			ALL: "transport.vehicles.all",
			VIEW: "transport.vehicles.view",
			CREATE: "transport.vehicles.create",
			EDIT: "transport.vehicles.edit",
			DELETE: "transport.vehicles.delete",
		},
		ASSIGNMENT: {
			ALL: "transport.assignment.all",
			VIEW: "transport.assignment.view",
			CREATE: "transport.assignment.create",
			EDIT: "transport.assignment.edit",
			DELETE: "transport.assignment.delete",
		},
		ATTENDANCE: {
			ALL: "transport.attendance.all",
			VIEW: "transport.attendance.view",
			CREATE: "transport.attendance.create",
			EDIT: "transport.attendance.edit",
			DELETE: "transport.attendance.delete",
		},
	},
	CANTEEN: {
		VIEW: "canteen.view",
		ALL: "canteen.all",
		MENU: {
			ALL: "canteen.menu.all",
			VIEW: "canteen.menu.view",
			CREATE: "canteen.menu.create",
			EDIT: "canteen.menu.edit",
			DELETE: "canteen.menu.delete",
		},
		SALES: {
			ALL: "canteen.sales.all",
			VIEW: "canteen.sales.view",
			CREATE: "canteen.sales.create",
			EDIT: "canteen.sales.edit",
			DELETE: "canteen.sales.delete",
		},
		EXPENSE: {
			ALL: "canteen.expense.all",
			VIEW: "canteen.expense.view",
			CREATE: "canteen.expense.create",
			EDIT: "canteen.expense.edit",
			DELETE: "canteen.expense.delete",
		},
	},
	REPORTS: {
		VIEW: "reports.view",
		ALL: "reports.all",
		ACADEMIC: {
			ALL: "reports.academic.all",
			VIEW: "reports.academic.view",
			CREATE: "reports.academic.create",
			EDIT: "reports.academic.edit",
			DELETE: "reports.academic.delete",
		},
		FINANCE: {
			ALL: "reports.finance.all",
			VIEW: "reports.finance.view",
			CREATE: "reports.finance.create",
			EDIT: "reports.finance.edit",
			DELETE: "reports.finance.delete",
		},
		STUDENT: {
			ALL: "reports.student.all",
			VIEW: "reports.student.view",
			CREATE: "reports.student.create",
			EDIT: "reports.student.edit",
			DELETE: "reports.student.delete",
		},
		SCHEDULED: {
			ALL: "reports.scheduled.all",
			VIEW: "reports.scheduled.view",
			CREATE: "reports.scheduled.create",
			EDIT: "reports.scheduled.edit",
			DELETE: "reports.scheduled.delete",
		},
	},
	ROLES: {
		VIEW: "roles.view",
		ALL: "roles.all",
		MANAGEMENT: {
			ALL: "roles.management.all",
			VIEW: "roles.management.view",
			CREATE: "roles.management.create",
			EDIT: "roles.management.edit",
			DELETE: "roles.management.delete",
		},
		MATRIX: {
			ALL: "roles.matrix.all",
			VIEW: "roles.matrix.view",
			CREATE: "roles.matrix.create",
			EDIT: "roles.matrix.edit",
			DELETE: "roles.matrix.delete",
		},
	},
	SETTINGS: {
		VIEW: "settings.view",
		ALL: "settings.all",
		PROFILE: {
			ALL: "settings.profile.all",
			VIEW: "settings.profile.view",
			CREATE: "settings.profile.create",
			EDIT: "settings.profile.edit",
			DELETE: "settings.profile.delete",
		},
		USERS: {
			ALL: "settings.users.all",
			VIEW: "settings.users.view",
			CREATE: "settings.users.create",
			EDIT: "settings.users.edit",
			DELETE: "settings.users.delete",
		},
		INTEGRATIONS: {
			ALL: "settings.integrations.all",
			VIEW: "settings.integrations.view",
			CREATE: "settings.integrations.create",
			EDIT: "settings.integrations.edit",
			DELETE: "settings.integrations.delete",
		},
		LOCALIZATION: {
			ALL: "settings.localization.all",
			VIEW: "settings.localization.view",
			CREATE: "settings.localization.create",
			EDIT: "settings.localization.edit",
			DELETE: "settings.localization.delete",
		},
		BACKUP: {
			ALL: "settings.backup.all",
			VIEW: "settings.backup.view",
			CREATE: "settings.backup.create",
			EDIT: "settings.backup.edit",
			DELETE: "settings.backup.delete",
		},
		AUDIT: {
			ALL: "settings.audit.all",
			VIEW: "settings.audit.view",
			CREATE: "settings.audit.create",
			EDIT: "settings.audit.edit",
			DELETE: "settings.audit.delete",
		},
	},
} as const;
