import {
	Activity,
	AlarmClockCheck,
	AlertCircle,
	ArrowRightLeft,
	Award,
	Banknote,
	BarChart3,
	BookMarked,
	BookOpen,
	BookType,
	Briefcase,
	Building2,
	Bus,
	CalendarDays,
	CalendarOff,
	Clipboard,
	ClipboardList,
	Coins,
	Database,
	DoorOpen,
	FileBadge2,
	Gift,
	Globe,
	GraduationCap,
	HeartHandshake,
	History,
	IdCard,
	Landmark,
	Laptop,
	LayoutDashboard,
	Library,
	Link,
	ListChecks,
	Mail,
	Megaphone,
	MessageSquare,
	Network,
	NotebookPen,
	PartyPopper,
	PieChart,
	Receipt,
	School,
	Settings,
	ShieldCheck,
	Store,
	Tags,
	TrendingUp,
	User,
	UserCheck,
	UserCog,
	Users,
	UsersRound,
} from "lucide-react";

import { PATHS } from "./paths.config";
import { PERMISSIONS } from "./permissions.config";

export type SidebarMenuType = {
	id: string;
	name: string;
	path: string;
	icon: React.ElementType;
	permissions: string[];
	matchPaths: string[];
	resetStore?: () => void;
	children?: SidebarMenuType[];
};

export const SidebarMenu: SidebarMenuType[] = [
	{
		id: "dashboard",
		name: "dashboard",
		path: PATHS.DASHBOARD,
		icon: LayoutDashboard,
		permissions: [PERMISSIONS.DASHBOARD.VIEW],
		matchPaths: [PATHS.DASHBOARD],
	},
	{
		id: "schools_management",
		name: "schools_management",
		path: PATHS.SCHOOLS_MANAGEMENT.ROOT,
		icon: School,
		permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.VIEW],
		matchPaths: [PATHS.SCHOOLS_MANAGEMENT.ROOT],
		children: [
			{
				id: "schools_management_schools",
				name: "schools_management_schools",
				path: PATHS.SCHOOLS_MANAGEMENT.SCHOOLS.ROOT,
				icon: School,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.SCHOOLS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.SCHOOLS.ROOT],
			},
			{
				id: "schools_management_subscription_plans",
				name: "schools_management_subscription_plans",
				path: PATHS.SCHOOLS_MANAGEMENT.SUBSCRIPTION_PLANS.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.SUBSCRIPTION_PLANS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.SUBSCRIPTION_PLANS.ROOT],
			},
			{
				id: "schools_management_vouchers",
				name: "schools_management_vouchers",
				path: PATHS.SCHOOLS_MANAGEMENT.VOUCHERS.ROOT,
				icon: Receipt,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.VOUCHERS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.VOUCHERS.ROOT],
			},
			{
				id: "schools_management_school_subscriptions",
				name: "schools_management_school_subscriptions",
				path: PATHS.SCHOOLS_MANAGEMENT.SCHOOL_SUBSCRIPTIONS.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.SCHOOL_SUBSCRIPTIONS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.SCHOOL_SUBSCRIPTIONS.ROOT],
			},
			{
				id: "schools_management_bank_accounts",
				name: "schools_management_bank_accounts",
				path: PATHS.SCHOOLS_MANAGEMENT.BANK_ACCOUNTS.ROOT,
				icon: Landmark,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.BANK_ACCOUNTS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.BANK_ACCOUNTS.ROOT],
			},
			{
				id: "schools_management_payments",
				name: "schools_management_payments",
				path: PATHS.SCHOOLS_MANAGEMENT.PAYMENTS.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.SCHOOLS_MANAGEMENT.PAYMENTS.VIEW],
				matchPaths: [PATHS.SCHOOLS_MANAGEMENT.PAYMENTS.ROOT],
			},
		],
	},
	{
		id: "academics",
		name: "academics",
		path: PATHS.ACADEMICS.ROOT,
		icon: BookOpen,
		permissions: [PERMISSIONS.ACADEMICS.VIEW],
		matchPaths: [PATHS.ACADEMICS.ROOT],
		children: [
			// Session is the umbrella every other academic entity is scoped to,
			// so it comes first — everything below is "set this up for a session".
			{
				id: "academics_sessions",
				name: "academics_sessions",
				path: PATHS.ACADEMICS.SESSIONS.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.ACADEMICS.SESSIONS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SESSIONS.ROOT],
			},
			// The term calendar for that session — holidays and notable dates
			// every other module should eventually be aware of.
			// Read-mostly overview merging Holidays + Events onto one grid —
			// the "multiple calendars, one glance" pattern. Listed first since
			// it's the landing view; the two specific management screens
			// (where you actually add/edit something) follow it.
			{
				id: "academics_school_calendar",
				name: "academics_school_calendar",
				path: PATHS.ACADEMICS.SCHOOL_CALENDAR.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.ACADEMICS.HOLIDAYS.VIEW, PERMISSIONS.EVENTS.SCHEDULING.VIEW],
				matchPaths: [PATHS.ACADEMICS.SCHOOL_CALENDAR.ROOT],
			},
			{
				id: "academics_holidays",
				name: "academics_holidays",
				path: PATHS.ACADEMICS.HOLIDAYS.ROOT,
				icon: CalendarOff,
				permissions: [PERMISSIONS.ACADEMICS.HOLIDAYS.VIEW],
				matchPaths: [PATHS.ACADEMICS.HOLIDAYS.ROOT],
			},
			// Structural setup: class -> section -> subject -> room -> shift,
			// each a building block the next depends on.
			{
				id: "academics_classes",
				name: "academics_classes",
				path: PATHS.ACADEMICS.CLASSES.ROOT,
				icon: Building2,
				permissions: [PERMISSIONS.ACADEMICS.CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.CLASSES.ROOT],
			},
			{
				id: "academics_sections",
				name: "academics_sections",
				path: PATHS.ACADEMICS.SECTIONS.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.ACADEMICS.CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.SECTIONS.ROOT],
			},
			{
				id: "academics_subjects",
				name: "academics_subjects",
				path: PATHS.ACADEMICS.SUBJECTS.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.ACADEMICS.SUBJECTS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SUBJECTS.ROOT],
			},
			{
				id: "academics_class_rooms",
				name: "academics_class_rooms",
				path: PATHS.ACADEMICS.CLASS_ROOMS.ROOT,
				icon: DoorOpen,
				permissions: [PERMISSIONS.ACADEMICS.CLASS_ROOMS.VIEW],
				matchPaths: [PATHS.ACADEMICS.CLASS_ROOMS.ROOT],
			},
			{
				id: "academics_shifts",
				name: "academics_shifts",
				path: PATHS.ACADEMICS.SHIFTS.ROOT,
				icon: AlarmClockCheck,
				permissions: [PERMISSIONS.ACADEMICS.SHIFTS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SHIFTS.ROOT],
			},
			// Ties the building blocks above together for one session.
			{
				id: "academics_session_class_setup",
				name: "academics_session_class_setup",
				path: PATHS.ACADEMICS.SESSION_CLASS_SETUP.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.ACADEMICS.CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.SESSION_CLASS_SETUP.ROOT],
			},
			{
				id: "academics_subject_teacher_assignments",
				name: "academics_subject_teacher_assignments",
				path: PATHS.ACADEMICS.SUBJECT_TEACHER_ASSIGNMENTS.ROOT,
				icon: UserCog,
				permissions: [PERMISSIONS.ACADEMICS.SUBJECT_TEACHER_ASSIGNMENTS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SUBJECT_TEACHER_ASSIGNMENTS.ROOT],
			},
			// Scheduling and curriculum, which depend on the setup above.
			{
				id: "academics_timetable",
				name: "academics_timetable",
				path: PATHS.ACADEMICS.TIMETABLE.ROOT,
				icon: AlarmClockCheck,
				permissions: [PERMISSIONS.ACADEMICS.TIMETABLE.VIEW],
				matchPaths: [PATHS.ACADEMICS.TIMETABLE.ROOT],
			},
			{
				id: "academics_syllabus",
				name: "academics_syllabus",
				path: PATHS.ACADEMICS.SYLLABUS.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.ACADEMICS.SYLLABUS.VIEW],
				matchPaths: [PATHS.ACADEMICS.SYLLABUS.ROOT],
			},
			{
				id: "academics_lesson_plans",
				name: "academics_lesson_plans",
				path: PATHS.ACADEMICS.LESSON_PLANS.ROOT,
				icon: NotebookPen,
				permissions: [PERMISSIONS.ACADEMICS.LESSON_PLANS.VIEW],
				matchPaths: [PATHS.ACADEMICS.LESSON_PLANS.ROOT],
			},
			// Day-to-day teaching activity, last since it happens continuously
			// once everything above exists.
			{
				id: "academics_homework",
				name: "academics_homework",
				path: PATHS.ACADEMICS.HOMEWORK.ROOT,
				icon: BookMarked,
				permissions: [PERMISSIONS.ACADEMICS.HOMEWORK.VIEW],
				matchPaths: [PATHS.ACADEMICS.HOMEWORK.ROOT],
			},
			{
				id: "academics_online_classes",
				name: "academics_online_classes",
				path: PATHS.ACADEMICS.ONLINE_CLASSES.ROOT,
				icon: Laptop,
				permissions: [PERMISSIONS.ACADEMICS.ONLINE_CLASSES.VIEW],
				matchPaths: [PATHS.ACADEMICS.ONLINE_CLASSES.ROOT],
			},
		],
	},
	{
		id: "admission",
		name: "admission",
		path: PATHS.ADMISSION.ROOT,
		icon: DoorOpen,
		permissions: [PERMISSIONS.ADMISSION.VIEW],
		matchPaths: [PATHS.ADMISSION.ROOT],
		children: [
			{
				id: "admission_new",
				name: "admission_new",
				path: PATHS.ADMISSION.NEW.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.ADMISSION.NEW.VIEW],
				matchPaths: [PATHS.ADMISSION.NEW.ROOT],
			},
			{
				id: "admission_list",
				name: "admission_list",
				path: PATHS.ADMISSION.LIST.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.ADMISSION.LIST.VIEW],
				matchPaths: [PATHS.ADMISSION.LIST.ROOT],
			},
			{
				id: "admission_portal",
				name: "admission_portal",
				path: PATHS.ADMISSION.PORTAL.ROOT,
				icon: Globe,
				permissions: [PERMISSIONS.ADMISSION.PORTAL.VIEW],
				matchPaths: [PATHS.ADMISSION.PORTAL.ROOT],
			},
			{
				id: "admission_settings",
				name: "admission_settings",
				path: PATHS.ADMISSION.SETTINGS.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.ADMISSION.SETTINGS.VIEW],
				matchPaths: [PATHS.ADMISSION.SETTINGS.ROOT],
			},
		],
	},
	{
		id: "students",
		name: "students",
		path: PATHS.STUDENTS.ROOT,
		icon: GraduationCap,
		permissions: [PERMISSIONS.STUDENTS.VIEW],
		matchPaths: [PATHS.STUDENTS.ROOT],
		children: [
			{
				id: "students_directory",
				name: "students_directory",
				path: PATHS.STUDENTS.DIRECTORY.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.STUDENTS.DIRECTORY.VIEW],
				matchPaths: [PATHS.STUDENTS.DIRECTORY.ROOT],
			},
			{
				id: "students_attendance",
				name: "students_attendance",
				path: PATHS.STUDENTS.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.STUDENTS.ATTENDANCE.VIEW],
				matchPaths: [PATHS.STUDENTS.ATTENDANCE.ROOT],
			},
			{
				id: "students_profile",
				name: "students_profile",
				path: PATHS.STUDENTS.PROFILE.ROOT,
				icon: User,
				permissions: [PERMISSIONS.STUDENTS.PROFILE.VIEW],
				matchPaths: [PATHS.STUDENTS.PROFILE.ROOT],
			},
			{
				id: "students_promotion",
				name: "students_promotion",
				path: PATHS.STUDENTS.PROMOTION.ROOT,
				icon: TrendingUp,
				permissions: [PERMISSIONS.STUDENTS.PROMOTION.VIEW],
				matchPaths: [PATHS.STUDENTS.PROMOTION.ROOT],
			},
			{
				id: "students_id_cards",
				name: "students_id_cards",
				path: PATHS.STUDENTS.ID_CARDS.ROOT,
				icon: IdCard,
				permissions: [PERMISSIONS.STUDENTS.ID_CARDS.VIEW],
				matchPaths: [PATHS.STUDENTS.ID_CARDS.ROOT],
			},
			{
				id: "students_certificates",
				name: "students_certificates",
				path: PATHS.STUDENTS.CERTIFICATES.ROOT,
				icon: Award,
				permissions: [PERMISSIONS.STUDENTS.CERTIFICATES.VIEW],
				matchPaths: [PATHS.STUDENTS.CERTIFICATES.ROOT],
			},
			{
				id: "students_behavior",
				name: "students_behavior",
				path: PATHS.STUDENTS.BEHAVIOR.ROOT,
				icon: HeartHandshake,
				permissions: [PERMISSIONS.STUDENTS.BEHAVIOR.VIEW],
				matchPaths: [PATHS.STUDENTS.BEHAVIOR.ROOT],
			},
		],
	},
	{
		id: "staff",
		name: "staff",
		path: PATHS.STAFF.ROOT,
		icon: Users,
		permissions: [PERMISSIONS.STAFF.VIEW],
		matchPaths: [PATHS.STAFF.ROOT],
		children: [
			{
				id: "staff_directory",
				name: "staff_directory",
				path: PATHS.STAFF.DIRECTORY.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.STAFF.DIRECTORY.VIEW],
				matchPaths: [PATHS.STAFF.DIRECTORY.ROOT],
			},
			{
				id: "staff_teachers",
				name: "staff_teachers",
				path: PATHS.STAFF.TEACHERS.ROOT,
				icon: UsersRound,
				permissions: [PERMISSIONS.STAFF.TEACHERS.VIEW],
				matchPaths: [PATHS.STAFF.TEACHERS.ROOT],
			},
			{
				id: "staff_attendance",
				name: "staff_attendance",
				path: PATHS.STAFF.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.STAFF.ATTENDANCE.VIEW],
				// The sub-pages must be listed or the nav item unhighlights on them.
				matchPaths: [
					PATHS.STAFF.ATTENDANCE.ROOT,
					PATHS.STAFF.ATTENDANCE.SETTINGS,
					PATHS.STAFF.ATTENDANCE.APPROVALS,
					PATHS.STAFF.ATTENDANCE.REPORT,
					PATHS.STAFF.ATTENDANCE.MY,
				],
			},
			{
				id: "staff_departments",
				name: "staff_departments",
				path: PATHS.STAFF.DEPARTMENTS.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.STAFF.DEPARTMENTS.VIEW],
				matchPaths: [PATHS.STAFF.DEPARTMENTS.ROOT],
			},
			{
				id: "staff_designations",
				name: "staff_designations",
				path: PATHS.STAFF.DESIGNATIONS.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.STAFF.DESIGNATIONS.VIEW],
				matchPaths: [PATHS.STAFF.DESIGNATIONS.ROOT],
			},
			{
				id: "staff_performance",
				name: "staff_performance",
				path: PATHS.STAFF.PERFORMANCE.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.STAFF.PERFORMANCE.VIEW],
				matchPaths: [PATHS.STAFF.PERFORMANCE.ROOT],
			},
		],
	},
	{
		id: "parents",
		name: "parents",
		path: PATHS.PARENTS.ROOT,
		icon: UsersRound,
		permissions: [PERMISSIONS.PARENTS.VIEW],
		matchPaths: [PATHS.PARENTS.ROOT],
		children: [
			{
				id: "parents_directory",
				name: "parents_directory",
				path: PATHS.PARENTS.DIRECTORY.ROOT,
				icon: UsersRound,
				permissions: [PERMISSIONS.PARENTS.DIRECTORY.VIEW],
				matchPaths: [PATHS.PARENTS.DIRECTORY.ROOT],
			},
			{
				id: "parents_portal",
				name: "parents_portal",
				path: PATHS.PARENTS.PORTAL.ROOT,
				icon: Laptop,
				permissions: [PERMISSIONS.PARENTS.PORTAL.VIEW],
				matchPaths: [PATHS.PARENTS.PORTAL.ROOT],
			},
		],
	},
	{
		id: "finance",
		name: "finance",
		path: PATHS.FINANCE.ROOT,
		icon: Banknote,
		permissions: [PERMISSIONS.FINANCE.VIEW],
		matchPaths: [PATHS.FINANCE.ROOT],
		children: [
			{
				id: "finance_fee_structure",
				name: "finance_fee_structure",
				path: PATHS.FINANCE.FEE_STRUCTURE.ROOT,
				icon: ListChecks,
				permissions: [PERMISSIONS.FINANCE.FEE_STRUCTURE.VIEW],
				matchPaths: [PATHS.FINANCE.FEE_STRUCTURE.ROOT],
			},
			{
				id: "finance_student_payments",
				name: "finance_student_payments",
				path: PATHS.FINANCE.STUDENT_PAYMENTS.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.FINANCE.STUDENT_PAYMENTS.VIEW],
				matchPaths: [PATHS.FINANCE.STUDENT_PAYMENTS.ROOT],
			},
			{
				id: "finance_expenses",
				name: "finance_expenses",
				path: PATHS.FINANCE.EXPENSES.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.FINANCE.EXPENSES.VIEW],
				matchPaths: [
					PATHS.FINANCE.EXPENSES.ROOT,
					PATHS.FINANCE.EXPENSES.CREATE,
					PATHS.FINANCE.EXPENSES.EDIT(":id"),
				],
			},
			{
				id: "finance_expense_categories",
				name: "finance_expense_categories",
				path: PATHS.FINANCE.EXPENSE_CATEGORIES.ROOT,
				icon: Tags,
				permissions: [PERMISSIONS.FINANCE.EXPENSE_CATEGORIES.VIEW],
				matchPaths: [
					PATHS.FINANCE.EXPENSE_CATEGORIES.ROOT,
					PATHS.FINANCE.EXPENSE_CATEGORIES.CREATE,
					PATHS.FINANCE.EXPENSE_CATEGORIES.EDIT(":id"),
				],
			},
			{
				id: "finance_profit_loss",
				name: "finance_profit_loss",
				path: PATHS.FINANCE.PROFIT_LOSS.ROOT,
				icon: TrendingUp,
				permissions: [PERMISSIONS.FINANCE.PROFIT_LOSS.VIEW],
				matchPaths: [PATHS.FINANCE.PROFIT_LOSS.ROOT],
			},
			{
				id: "finance_ledger",
				name: "finance_ledger",
				path: PATHS.FINANCE.LEDGER.ROOT,
				icon: BookType,
				permissions: [PERMISSIONS.FINANCE.LEDGER.VIEW],
				matchPaths: [PATHS.FINANCE.LEDGER.ROOT],
			},
			{
				id: "finance_scholarships",
				name: "finance_scholarships",
				path: PATHS.FINANCE.SCHOLARSHIPS.ROOT,
				icon: Gift,
				permissions: [PERMISSIONS.FINANCE.SCHOLARSHIPS.VIEW],
				matchPaths: [PATHS.FINANCE.SCHOLARSHIPS.ROOT],
			},
		],
	},
	{
		id: "hr",
		name: "hr",
		path: PATHS.HR.ROOT,
		icon: Briefcase,
		permissions: [PERMISSIONS.HR.VIEW],
		matchPaths: [PATHS.HR.ROOT],
		children: [
			{
				id: "hr_leave",
				name: "hr_leave",
				path: PATHS.HR.LEAVE.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.HR.LEAVE.VIEW],
				matchPaths: [PATHS.HR.LEAVE.ROOT],
			},
			{
				id: "hr_loan",
				name: "hr_loan",
				path: PATHS.HR.LOAN.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.HR.LOAN.VIEW],
				matchPaths: [PATHS.HR.LOAN.ROOT],
			},
			{
				id: "hr_appraisal",
				name: "hr_appraisal",
				path: PATHS.HR.APPRAISAL.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.HR.APPRAISAL.VIEW],
				matchPaths: [PATHS.HR.APPRAISAL.ROOT],
			},
		],
	},
	{
		id: "examinations",
		name: "examinations",
		path: PATHS.EXAMINATIONS.ROOT,
		icon: ClipboardList,
		permissions: [PERMISSIONS.EXAMINATIONS.VIEW],
		matchPaths: [PATHS.EXAMINATIONS.ROOT],
		children: [
			{
				id: "examinations_schedule",
				name: "examinations_schedule",
				path: PATHS.EXAMINATIONS.SCHEDULE.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.EXAMINATIONS.SCHEDULE.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.SCHEDULE.ROOT],
			},
			{
				id: "examinations_calendar",
				name: "examinations_calendar",
				path: PATHS.EXAMINATIONS.CALENDAR.ROOT,
				icon: CalendarDays,
				// Read-only view of data the Schedule module owns, so it rides on
				// the same VIEW permission rather than inventing one to grant.
				permissions: [PERMISSIONS.EXAMINATIONS.SCHEDULE.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.CALENDAR.ROOT],
			},
			{
				id: "examinations_routine",
				name: "examinations_routine",
				path: PATHS.EXAMINATIONS.ROUTINE.ROOT,
				icon: AlarmClockCheck,
				permissions: [PERMISSIONS.EXAMINATIONS.SCHEDULE.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.ROUTINE.ROOT],
			},
			{
				id: "examinations_marks",
				name: "examinations_marks",
				path: PATHS.EXAMINATIONS.MARKS.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.EXAMINATIONS.MARKS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.MARKS.ROOT],
			},
			{
				id: "examinations_results",
				name: "examinations_results",
				path: PATHS.EXAMINATIONS.RESULTS.ROOT,
				icon: Activity,
				permissions: [PERMISSIONS.EXAMINATIONS.RESULTS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.RESULTS.ROOT],
			},
			{
				id: "examinations_report_cards",
				name: "examinations_report_cards",
				path: PATHS.EXAMINATIONS.REPORT_CARDS.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.EXAMINATIONS.REPORT_CARDS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.REPORT_CARDS.ROOT],
			},
			{
				id: "examinations_question_bank",
				name: "examinations_question_bank",
				path: PATHS.EXAMINATIONS.QUESTION_BANK.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.EXAMINATIONS.QUESTION_BANK.VIEW],
				matchPaths: [
					PATHS.EXAMINATIONS.QUESTION_BANK.ROOT,
					PATHS.EXAMINATIONS.QUESTION_BANK.CREATE,
					PATHS.EXAMINATIONS.QUESTION_BANK.EDIT(":id"),
				],
			},
			{
				id: "examinations_settings",
				name: "examinations_settings",
				path: PATHS.EXAMINATIONS.SETTINGS.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.EXAMINATIONS.SETTINGS.VIEW],
				matchPaths: [PATHS.EXAMINATIONS.SETTINGS.ROOT],
			},
		],
	},
	{
		id: "library",
		name: "library",
		path: PATHS.LIBRARY.ROOT,
		icon: Library,
		permissions: [PERMISSIONS.LIBRARY.VIEW],
		matchPaths: [PATHS.LIBRARY.ROOT],
		children: [
			{
				id: "library_catalog",
				name: "library_catalog",
				path: PATHS.LIBRARY.CATALOG.ROOT,
				icon: BookOpen,
				permissions: [PERMISSIONS.LIBRARY.CATALOG.VIEW],
				matchPaths: [PATHS.LIBRARY.CATALOG.ROOT],
			},
			{
				id: "library_issue_return",
				name: "library_issue_return",
				path: PATHS.LIBRARY.ISSUE_RETURN.ROOT,
				icon: ArrowRightLeft,
				permissions: [PERMISSIONS.LIBRARY.ISSUE_RETURN.VIEW],
				matchPaths: [PATHS.LIBRARY.ISSUE_RETURN.ROOT],
			},
			{
				id: "library_fines",
				name: "library_fines",
				path: PATHS.LIBRARY.FINES.ROOT,
				icon: Coins,
				permissions: [PERMISSIONS.LIBRARY.FINES.VIEW],
				matchPaths: [PATHS.LIBRARY.FINES.ROOT],
			},
			{
				id: "library_reports",
				name: "library_reports",
				path: PATHS.LIBRARY.REPORTS.ROOT,
				icon: BarChart3,
				permissions: [PERMISSIONS.LIBRARY.REPORTS.VIEW],
				matchPaths: [PATHS.LIBRARY.REPORTS.ROOT],
			},
			{
				id: "library_settings",
				name: "library_settings",
				path: PATHS.LIBRARY.SETTINGS.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.LIBRARY.SETTINGS],
				matchPaths: [PATHS.LIBRARY.SETTINGS.ROOT],
			},
		],
	},
	{
		id: "inventory",
		name: "inventory",
		path: PATHS.INVENTORY.ROOT,
		icon: Store,
		permissions: [PERMISSIONS.INVENTORY.VIEW],
		matchPaths: [PATHS.INVENTORY.ROOT],
		children: [
			{
				id: "inventory_overview",
				name: "inventory_overview",
				path: PATHS.INVENTORY.OVERVIEW,
				icon: LayoutDashboard,
				permissions: [PERMISSIONS.INVENTORY.VIEW],
				matchPaths: [PATHS.INVENTORY.OVERVIEW],
			},
			{
				id: "inventory_categories",
				name: "inventory_categories",
				path: PATHS.INVENTORY.CATEGORIES.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.INVENTORY.CATEGORIES.VIEW],
				matchPaths: [PATHS.INVENTORY.CATEGORIES.ROOT],
			},
			{
				id: "inventory_items",
				name: "inventory_items",
				path: PATHS.INVENTORY.ITEMS.ROOT,
				icon: Database,
				permissions: [PERMISSIONS.INVENTORY.ITEMS.VIEW],
				matchPaths: [PATHS.INVENTORY.ITEMS.ROOT],
			},
			{
				id: "inventory_locations",
				name: "inventory_locations",
				path: PATHS.INVENTORY.LOCATIONS.ROOT,
				icon: Building2,
				permissions: [PERMISSIONS.INVENTORY.LOCATIONS.VIEW],
				matchPaths: [PATHS.INVENTORY.LOCATIONS.ROOT],
			},
			{
				id: "inventory_stock",
				name: "inventory_stock",
				path: PATHS.INVENTORY.STOCK.ROOT,
				icon: Store,
				permissions: [PERMISSIONS.INVENTORY.STOCK.VIEW],
				matchPaths: [PATHS.INVENTORY.STOCK.ROOT],
			},
			{
				id: "inventory_assets",
				name: "inventory_assets",
				path: PATHS.INVENTORY.ASSETS.ROOT,
				icon: Laptop,
				permissions: [PERMISSIONS.INVENTORY.ASSETS.VIEW],
				matchPaths: [PATHS.INVENTORY.ASSETS.ROOT],
			},
			{
				id: "inventory_movements",
				name: "inventory_movements",
				path: PATHS.INVENTORY.MOVEMENTS.ROOT,
				icon: History,
				permissions: [PERMISSIONS.INVENTORY.MOVEMENTS.VIEW],
				matchPaths: [PATHS.INVENTORY.MOVEMENTS.ROOT],
			},
			{
				id: "inventory_maintenance",
				name: "inventory_maintenance",
				path: PATHS.INVENTORY.MAINTENANCE.ROOT,
				icon: Settings,
				permissions: [PERMISSIONS.INVENTORY.MAINTENANCE.VIEW],
				matchPaths: [PATHS.INVENTORY.MAINTENANCE.ROOT],
			},
			{
				id: "inventory_audit_logs",
				name: "inventory_audit_logs",
				path: PATHS.INVENTORY.AUDIT_LOGS.ROOT,
				icon: History,
				permissions: [PERMISSIONS.INVENTORY.MOVEMENTS.VIEW],
				matchPaths: [PATHS.INVENTORY.AUDIT_LOGS.ROOT],
			},
		],
	},
	{
		id: "communications",
		name: "communications",
		path: PATHS.COMMUNICATIONS.ROOT,
		icon: Megaphone,
		permissions: [PERMISSIONS.COMMUNICATIONS.VIEW],
		matchPaths: [PATHS.COMMUNICATIONS.ROOT],
		children: [
			{
				id: "communications_announcements",
				name: "communications_announcements",
				path: PATHS.COMMUNICATIONS.ANNOUNCEMENTS.ROOT,
				icon: Megaphone,
				permissions: [PERMISSIONS.COMMUNICATIONS.ANNOUNCEMENTS.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.ANNOUNCEMENTS.ROOT],
			},
			{
				id: "communications_notice_board",
				name: "communications_notice_board",
				path: PATHS.COMMUNICATIONS.NOTICE_BOARD.ROOT,
				icon: Clipboard,
				permissions: [PERMISSIONS.COMMUNICATIONS.NOTICE_BOARD.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.NOTICE_BOARD.ROOT],
			},
			{
				id: "communications_messages",
				name: "communications_messages",
				path: PATHS.COMMUNICATIONS.MESSAGES.ROOT,
				icon: MessageSquare,
				permissions: [PERMISSIONS.COMMUNICATIONS.MESSAGES.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.MESSAGES.ROOT],
			},
			{
				id: "communications_complaints",
				name: "communications_complaints",
				path: PATHS.COMMUNICATIONS.COMPLAINTS.ROOT,
				icon: AlertCircle,
				permissions: [PERMISSIONS.COMMUNICATIONS.COMPLAINTS.VIEW],
				matchPaths: [PATHS.COMMUNICATIONS.COMPLAINTS.ROOT],
			},
		],
	},
	{
		id: "events",
		name: "events",
		path: PATHS.EVENTS.ROOT,
		icon: CalendarDays,
		permissions: [PERMISSIONS.EVENTS.VIEW],
		matchPaths: [PATHS.EVENTS.ROOT],
		children: [
			{
				id: "events_scheduling",
				name: "events_scheduling",
				path: PATHS.EVENTS.SCHEDULING.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.EVENTS.SCHEDULING.VIEW],
				matchPaths: [PATHS.EVENTS.SCHEDULING.ROOT],
			},
			{
				id: "events_participants",
				name: "events_participants",
				path: PATHS.EVENTS.PARTICIPANTS.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.EVENTS.PARTICIPANTS.VIEW],
				matchPaths: [PATHS.EVENTS.PARTICIPANTS.ROOT],
			},
			{
				id: "events_gallery",
				name: "events_gallery",
				path: PATHS.EVENTS.GALLERY.ROOT,
				icon: FileBadge2,
				permissions: [PERMISSIONS.EVENTS.GALLERY.VIEW],
				matchPaths: [PATHS.EVENTS.GALLERY.ROOT],
			},
		],
	},
	{
		id: "transport",
		name: "transport",
		path: PATHS.TRANSPORT.ROOT,
		icon: Bus,
		permissions: [PERMISSIONS.TRANSPORT.VIEW],
		matchPaths: [PATHS.TRANSPORT.ROOT],
		children: [
			{
				id: "transport_routes",
				name: "transport_routes",
				path: PATHS.TRANSPORT.ROUTES.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.TRANSPORT.ROUTES.VIEW],
				matchPaths: [PATHS.TRANSPORT.ROUTES.ROOT],
			},
			{
				id: "transport_vehicles",
				name: "transport_vehicles",
				path: PATHS.TRANSPORT.VEHICLES.ROOT,
				icon: Bus,
				permissions: [PERMISSIONS.TRANSPORT.VEHICLES.VIEW],
				matchPaths: [PATHS.TRANSPORT.VEHICLES.ROOT],
			},
			{
				id: "transport_assignment",
				name: "transport_assignment",
				path: PATHS.TRANSPORT.ASSIGNMENT.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.TRANSPORT.ASSIGNMENT.VIEW],
				matchPaths: [PATHS.TRANSPORT.ASSIGNMENT.ROOT],
			},
			{
				id: "transport_attendance",
				name: "transport_attendance",
				path: PATHS.TRANSPORT.ATTENDANCE.ROOT,
				icon: UserCheck,
				permissions: [PERMISSIONS.TRANSPORT.ATTENDANCE.VIEW],
				matchPaths: [PATHS.TRANSPORT.ATTENDANCE.ROOT],
			},
		],
	},
	{
		id: "canteen",
		name: "canteen",
		path: PATHS.CANTEEN.ROOT,
		icon: Store,
		permissions: [PERMISSIONS.CANTEEN.VIEW],
		matchPaths: [PATHS.CANTEEN.ROOT],
		children: [
			{
				id: "canteen_menu",
				name: "canteen_menu",
				path: PATHS.CANTEEN.MENU.ROOT,
				icon: ClipboardList,
				permissions: [PERMISSIONS.CANTEEN.MENU.VIEW],
				matchPaths: [PATHS.CANTEEN.MENU.ROOT],
			},
			{
				id: "canteen_sales",
				name: "canteen_sales",
				path: PATHS.CANTEEN.SALES.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.CANTEEN.SALES.VIEW],
				matchPaths: [PATHS.CANTEEN.SALES.ROOT],
			},
			{
				id: "canteen_expense",
				name: "canteen_expense",
				path: PATHS.CANTEEN.EXPENSE.ROOT,
				icon: Banknote,
				permissions: [PERMISSIONS.CANTEEN.EXPENSE.VIEW],
				matchPaths: [PATHS.CANTEEN.EXPENSE.ROOT],
			},
		],
	},
	{
		id: "reports",
		name: "reports",
		path: PATHS.REPORTS.ROOT,
		icon: BarChart3,
		permissions: [PERMISSIONS.REPORTS.VIEW],
		matchPaths: [PATHS.REPORTS.ROOT],
		children: [
			{
				id: "reports_academic",
				name: "reports_academic",
				path: PATHS.REPORTS.ACADEMIC.ROOT,
				icon: BarChart3,
				permissions: [PERMISSIONS.REPORTS.ACADEMIC.VIEW],
				matchPaths: [PATHS.REPORTS.ACADEMIC.ROOT],
			},
			{
				id: "reports_finance",
				name: "reports_finance",
				path: PATHS.REPORTS.FINANCE.ROOT,
				icon: PieChart,
				permissions: [PERMISSIONS.REPORTS.FINANCE.VIEW],
				matchPaths: [PATHS.REPORTS.FINANCE.ROOT],
			},
			{
				id: "reports_student",
				name: "reports_student",
				path: PATHS.REPORTS.STUDENT.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.REPORTS.STUDENT.VIEW],
				matchPaths: [PATHS.REPORTS.STUDENT.ROOT],
			},
			{
				id: "reports_scheduled",
				name: "reports_scheduled",
				path: PATHS.REPORTS.SCHEDULED.ROOT,
				icon: CalendarDays,
				permissions: [PERMISSIONS.REPORTS.SCHEDULED.VIEW],
				matchPaths: [PATHS.REPORTS.SCHEDULED.ROOT],
			},
		],
	},
	{
		id: "roles",
		name: "roles",
		path: PATHS.ROLES.ROOT,
		icon: ShieldCheck,
		permissions: [PERMISSIONS.ROLES.VIEW],
		matchPaths: [PATHS.ROLES.ROOT],
		children: [
			{
				id: "roles_management",
				name: "roles_management",
				path: PATHS.ROLES.MANAGEMENT.ROOT,
				icon: ShieldCheck,
				permissions: [PERMISSIONS.ROLES.MANAGEMENT.VIEW],
				matchPaths: [PATHS.ROLES.MANAGEMENT.ROOT],
			},
			{
				id: "roles_matrix",
				name: "roles_matrix",
				path: PATHS.ROLES.MATRIX.ROOT,
				icon: Network,
				permissions: [PERMISSIONS.ROLES.MATRIX.VIEW],
				matchPaths: [PATHS.ROLES.MATRIX.ROOT],
			},
		],
	},

	{
		id: "settings",
		name: "settings",
		path: PATHS.SETTINGS.ROOT,
		icon: Settings,
		permissions: [PERMISSIONS.SETTINGS.VIEW],
		matchPaths: [PATHS.SETTINGS.ROOT],
		children: [
			{
				id: "settings_profile",
				name: "settings_profile",
				path: PATHS.SETTINGS.PROFILE.ROOT,
				icon: School,
				permissions: [PERMISSIONS.SETTINGS.PROFILE.VIEW],
				matchPaths: [PATHS.SETTINGS.PROFILE.ROOT],
			},
			{
				id: "settings_users",
				name: "settings_users",
				path: PATHS.SETTINGS.USERS.ROOT,
				icon: Users,
				permissions: [PERMISSIONS.SETTINGS.USERS.VIEW],
				matchPaths: [PATHS.SETTINGS.USERS.ROOT],
			},
			{
				id: "settings_integrations",
				name: "settings_integrations",
				path: PATHS.SETTINGS.INTEGRATIONS.ROOT,
				icon: Link,
				permissions: [PERMISSIONS.SETTINGS.INTEGRATIONS.VIEW],
				matchPaths: [PATHS.SETTINGS.INTEGRATIONS.ROOT],
			},
			{
				id: "settings_payment_methods",
				name: "settings_payment_methods",
				path: PATHS.SETTINGS.PAYMENT_METHODS.ROOT,
				icon: Receipt,
				permissions: [PERMISSIONS.SETTINGS.PAYMENT_METHODS.VIEW],
				matchPaths: [PATHS.SETTINGS.PAYMENT_METHODS.ROOT],
			},
			{
				id: "settings_school_mail",
				name: "settings_school_mail",
				path: PATHS.SETTINGS.SCHOOL_MAIL.ROOT,
				icon: Mail,
				permissions: [PERMISSIONS.SETTINGS.MAIL_SETTINGS.VIEW],
				matchPaths: [PATHS.SETTINGS.SCHOOL_MAIL.ROOT],
			},
			{
				id: "settings_software_mail",
				name: "settings_software_mail",
				path: PATHS.SETTINGS.SOFTWARE_MAIL.ROOT,
				icon: Mail,
				permissions: [PERMISSIONS.SETTINGS.MAIL_SETTINGS.VIEW],
				matchPaths: [PATHS.SETTINGS.SOFTWARE_MAIL.ROOT],
			},
			{
				id: "settings_localization",
				name: "settings_localization",
				path: PATHS.SETTINGS.LOCALIZATION.ROOT,
				icon: Globe,
				permissions: [PERMISSIONS.SETTINGS.LOCALIZATION.VIEW],
				matchPaths: [PATHS.SETTINGS.LOCALIZATION.ROOT],
			},
			{
				id: "settings_backup",
				name: "settings_backup",
				path: PATHS.SETTINGS.BACKUP.ROOT,
				icon: Database,
				permissions: [PERMISSIONS.SETTINGS.BACKUP.VIEW],
				matchPaths: [PATHS.SETTINGS.BACKUP.ROOT],
			},
			{
				id: "settings_audit",
				name: "settings_audit",
				path: PATHS.SETTINGS.AUDIT.ROOT,
				icon: History,
				permissions: [PERMISSIONS.SETTINGS.AUDIT.VIEW],
				matchPaths: [PATHS.SETTINGS.AUDIT.ROOT],
			},
		],
	},
];
