import { PATHS } from "@/shared/configs/paths.config";
import { PERMISSIONS } from "@/shared/configs/permissions.config";
import { InventoryResource } from "../hooks/use-inventory";

export type InventoryModuleKey =
	| "categories"
	| "items"
	| "locations"
	| "stock"
	| "assets"
	| "movements"
	| "maintenance"
	| "auditLogs";

export const inventoryModules: Record<
	InventoryModuleKey,
	{
		resource: InventoryResource;
		titleKey: string;
		descriptionKey: string;
		rootPath: string;
		createPath?: string;
		editPath?: (id: string) => string;
		permissions: {
			view: string[];
			create: string[];
			edit: string[];
			delete: string[];
		};
	}
> = {
	categories: {
		resource: "categories",
		titleKey: "categoriesTitle",
		descriptionKey: "categoriesDescription",
		rootPath: PATHS.INVENTORY.CATEGORIES.ROOT,
		createPath: PATHS.INVENTORY.CATEGORIES.CREATE,
		editPath: PATHS.INVENTORY.CATEGORIES.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.CATEGORIES.VIEW, PERMISSIONS.INVENTORY.CATEGORIES.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.CATEGORIES.CREATE, PERMISSIONS.INVENTORY.CATEGORIES.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.CATEGORIES.EDIT, PERMISSIONS.INVENTORY.CATEGORIES.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.CATEGORIES.DELETE, PERMISSIONS.INVENTORY.CATEGORIES.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	items: {
		resource: "items",
		titleKey: "itemsTitle",
		descriptionKey: "itemsDescription",
		rootPath: PATHS.INVENTORY.ITEMS.ROOT,
		createPath: PATHS.INVENTORY.ITEMS.CREATE,
		editPath: PATHS.INVENTORY.ITEMS.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.ITEMS.VIEW, PERMISSIONS.INVENTORY.ITEMS.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.ITEMS.CREATE, PERMISSIONS.INVENTORY.ITEMS.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.ITEMS.EDIT, PERMISSIONS.INVENTORY.ITEMS.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.ITEMS.DELETE, PERMISSIONS.INVENTORY.ITEMS.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	locations: {
		resource: "locations",
		titleKey: "locationsTitle",
		descriptionKey: "locationsDescription",
		rootPath: PATHS.INVENTORY.LOCATIONS.ROOT,
		createPath: PATHS.INVENTORY.LOCATIONS.CREATE,
		editPath: PATHS.INVENTORY.LOCATIONS.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.LOCATIONS.VIEW, PERMISSIONS.INVENTORY.LOCATIONS.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.LOCATIONS.CREATE, PERMISSIONS.INVENTORY.LOCATIONS.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.LOCATIONS.EDIT, PERMISSIONS.INVENTORY.LOCATIONS.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.LOCATIONS.DELETE, PERMISSIONS.INVENTORY.LOCATIONS.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	stock: {
		resource: "stock-batches",
		titleKey: "stockTitle",
		descriptionKey: "stockDescription",
		rootPath: PATHS.INVENTORY.STOCK.ROOT,
		createPath: PATHS.INVENTORY.STOCK.CREATE,
		editPath: PATHS.INVENTORY.STOCK.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.STOCK.VIEW, PERMISSIONS.INVENTORY.STOCK.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.STOCK.CREATE, PERMISSIONS.INVENTORY.STOCK.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.STOCK.EDIT, PERMISSIONS.INVENTORY.STOCK.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.STOCK.DELETE, PERMISSIONS.INVENTORY.STOCK.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	assets: {
		resource: "assets",
		titleKey: "assetsTitle",
		descriptionKey: "assetsDescription",
		rootPath: PATHS.INVENTORY.ASSETS.ROOT,
		createPath: PATHS.INVENTORY.ASSETS.CREATE,
		editPath: PATHS.INVENTORY.ASSETS.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.ASSETS.VIEW, PERMISSIONS.INVENTORY.ASSETS.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.ASSETS.CREATE, PERMISSIONS.INVENTORY.ASSETS.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.ASSETS.EDIT, PERMISSIONS.INVENTORY.ASSETS.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.ASSETS.DELETE, PERMISSIONS.INVENTORY.ASSETS.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	movements: {
		resource: "movements",
		titleKey: "movementsTitle",
		descriptionKey: "movementsDescription",
		rootPath: PATHS.INVENTORY.MOVEMENTS.ROOT,
		createPath: PATHS.INVENTORY.MOVEMENTS.CREATE,
		permissions: {
			view: [PERMISSIONS.INVENTORY.MOVEMENTS.VIEW, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.MOVEMENTS.CREATE, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.MOVEMENTS.EDIT, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.MOVEMENTS.DELETE, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	maintenance: {
		resource: "maintenance",
		titleKey: "maintenanceTitle",
		descriptionKey: "maintenanceDescription",
		rootPath: PATHS.INVENTORY.MAINTENANCE.ROOT,
		createPath: PATHS.INVENTORY.MAINTENANCE.CREATE,
		editPath: PATHS.INVENTORY.MAINTENANCE.EDIT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.MAINTENANCE.VIEW, PERMISSIONS.INVENTORY.MAINTENANCE.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.MAINTENANCE.CREATE, PERMISSIONS.INVENTORY.MAINTENANCE.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.MAINTENANCE.EDIT, PERMISSIONS.INVENTORY.MAINTENANCE.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.MAINTENANCE.DELETE, PERMISSIONS.INVENTORY.MAINTENANCE.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
	auditLogs: {
		resource: "audit-logs",
		titleKey: "auditLogsTitle",
		descriptionKey: "auditLogsDescription",
		rootPath: PATHS.INVENTORY.AUDIT_LOGS.ROOT,
		permissions: {
			view: [PERMISSIONS.INVENTORY.MOVEMENTS.VIEW, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			create: [PERMISSIONS.INVENTORY.MOVEMENTS.CREATE, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			edit: [PERMISSIONS.INVENTORY.MOVEMENTS.EDIT, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
			delete: [PERMISSIONS.INVENTORY.MOVEMENTS.DELETE, PERMISSIONS.INVENTORY.MOVEMENTS.ALL, PERMISSIONS.INVENTORY.ALL],
		},
	},
};
