export enum SubjectTypeEnum {
	MANDATORY = "MANDATORY",
	OPTIONAL = "OPTIONAL",
	PRACTICAL = "PRACTICAL",
	FOURTH_SUBJECT = "FOURTH_SUBJECT",
	RELIGION = "RELIGION",
	GROUP_BASED = "GROUP_BASED",
}

export enum SubjectMarkDivisionEnum {
	WRITTEN = "WRITTEN",
	WRITTEN_MCQ = "WRITTEN_MCQ",
	WRITTEN_MCQ_PRACTICAL = "WRITTEN_MCQ_PRACTICAL",
}

export enum StatusEnum {
	ACTIVE = "ACTIVE",
	INACTIVE = "INACTIVE",
	PENDING = "PENDING",
}

export enum BaseRoleEnum {
	DEVELOPER = "DEVELOPER",
	SUPER_ADMIN = "SUPER_ADMIN",
	SCHOOL_ADMIN = "SCHOOL_ADMIN",
	TEACHER = "TEACHER",
	STUDENT = "STUDENT",
	PARENT = "PARENT",
	USER = "USER",
}
